### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by juniorb2ss** [ubc/docker-canvas#4]
Why best way to enable ssl in docker?

I'm using docker, s3 and cloudfront for reverse proxy, but some links in canvas is generated in http, not https.

In `deploy/domain.yml` ssl config has true value.

Can help me?

**Comment by andrew-gardener** [comment]
@juniorb2ss This repo is currently setup for running canvas integration testing locally with various LTI tools and shouldn't be used for production environments.

With that said, I haven't looked into setting up ssl for Canvas installation since I haven't needed it yet.

You might have better luck asking the folks over in https://github.com/instructure/canvas-lms
